version: 2
updates:
- package-ecosystem: pip
  directory: /
  schedule:
    interval: weekly
    day: saturday
    time: "02:00"
    timezone: "Europe/London"
- package-ecosystem: github-actions
  directory: /
  schedule:
    interval: weekly
    day: saturday
    time: "02:00"
    timezone: "Europe/London"
