version: '3.8'

services:
  pfsenseclient:
    build:
      context: .
      dockerfile: docker/local/Dockerfile
    volumes:
      - ./pfsense_api_client:/app/pfsense_api_client
      - ./tests:/app/tests
    command: pytest tests/
    stdin_open: true
    tty: true
