site_name: pyfsense_client
theme:
  name: material
  features:
    - navigation.expand
plugins:
- search:
- mkdocstrings:
    default_handler: python
    handlers:
      python:
        # rendering:
        show_source: true
    watch:
    - pyfsense_client/
nav:
- Home: README.md
- Client Module: client.md
- Mixins:
  - Firewall: mixin_firewall.md
  - Service: mixin_service.md
  - Status: mixin_status.md
  - System: mixin_system.md




repo_name: devinbarry/pyfsense-client
repo_url: https://github.com/devinbarry/pyfsense-client
site_url: https://yaleman.github.io/pfsense-api-client/
