name: pylint

"on":
  push:
    branches:
      - main  # Set a branch to deploy
  pull_request:

jobs:
  pylint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.2
        with:
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python --version
          python -m pip install --upgrade pip
          python -m pip install --quiet --no-cache-dir -r requirements/requirements_dev.txt
          python -m pip install pylint  # Ensure pylint is installed

      - name: Running pylint
        run: |
          python -m pylint $(basename $(pwd) | sed -E 's/-/_/g')
          python -m pylint tests/
